baseURL = "http://meditations.is/"
languageCode = "en-us"
title = "Meditations"
theme = "paper"
author = "Hugo de Groot"
paginate = 6
ignoreErrors = ["error-remote-getjson"]

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'YOUR_GITHUB_ID'                 # github.com/hugodegroot
  instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/hugodegro.ot

  # home page profile
  avatar = 'https://media.licdn.com/dms/image/C5603AQGinxCbn0FlOw/profile-displayphoto-shrink_800_800/0/1517433327901?e=1680739200&v=beta&t=7YixIk1twBebBaBYO5Sw2cWZF0RGLyNOuGpRvlQqc6g'                 # gravatar email or image url
  name = 'Hugo de Groot'
  bio = 'My thoughts about the world'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

  [menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
